### ISSUE TITLE
Question about using `ruff_fix = true`

### ISSUE THREAD

**Issue by afuetterer** [provinzkraut/unasyncd#27]
Hi there, 

if I use the config option `ruff_fix = true` to remove unused imports, the removal works fine. But I am running into other issues.

Your docs say 
> It will use the existing ruff configuration for this to ensure the fixes applied to adhere to the rules used throughout the project.

If I run unasyncd as a pre-commit hook with ruff under additional_dependencies, I get errors coming from ruff.

I have ignored pydocstyle (D) for my "tests" directory, but now I get a couple of errors for the generated files, e.g.

```
-:93:5: D103 Missing docstring in public function
   |
93 | def test_client_handles_server_error(client: Client, mock_server_error: Route) -> None:
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ D103
```

If I run `ruff check`, no such errors occur, because D/D103 is ignored.

Is this a bug?

**Comment by provinzkraut** [comment]
Someone reported a similar issue as well. I think this might have something to do with a recent ruff update, because on their setup, this wasn't an issue before upgrading to ruff `0.5`. Could  you check with an older ruff version?

Unasyncd really isn't doing anything fancy here. It just invokes `ruff` on the file before writing it to disk :shrug:

**Comment by provinzkraut** [comment]
@afuetterer Suspecting that it has something to do with per-file configuration, can you check out if the fix I implemented in #28 solves your issue?

**Comment by afuetterer** [comment]
Yes, will do. Using the main branch, as it is not released yet, right?

Your description sounds about right. How should ruff know about the per files ignore rules, if it does not know the file names? I think it will work out with your fix.

Will report soon.

**Comment by afuetterer** [comment]
Yes, it works. Thanks for fixing this so fast. Will you publish a release for this? pre-commit complains about using a branch name as rev.

**Comment by provinzkraut** [comment]
> Yes, it works. Thanks for fixing this so fast. Will you publish a release for this? pre-commit complains about using a branch name as rev.

Yes, I'll make a release in the next couple days

**Comment by afuetterer** [comment]
Awesome.

**Comment by provinzkraut** [comment]
@afuetterer I just release v0.7.3 with the fix.

**Comment by afuetterer** [comment]
I have a follow up question about the usage.

I enable the unasyncd pre-commit hook in CI, where there is no unasyncd cache present, of course.

unasyncd changes a file, resulting in the pre-commit hook to fail, but I also have ruff and ruff format in my pre-commit hooks. So the file content does not change, because "ruff format" fixes the change of unasynd. But CI still fails.

Do you have a recommendation for this situation? Otherwise I just skip the check in CI.

What happens is this:

- I allow a line-length of 120.
- there is e.g. a line like this:
`def test_client_list_repositories_default_return_type(client: Client, mock_repository_list_route: Route) -> None:`
- unasynd with ruff_fix=True makes it "shorter":
```
def test_client_list_repositories_default_return_type(
    client: Client, mock_repository_list_route: Route
) -> None:
```
- ruff format makes it "longer" again:
`def test_client_list_repositories_default_return_type(client: Client, mock_repository_list_route: Route) -> None:`

Resulting in two failed pre-commit hooks in CI

**Comment by provinzkraut** [comment]
Ah, I think the issue here is that while unasyncd does `ruff check --fix`, it doesn't do `ruff format` (because it predates the ruff formatter :))

Should be an easy fix though to invoke that as well. If you're interested in creating a PR for this, contributions are welcome. Otherwise I'll probably get to it on the weekend.

**Comment by afuetterer** [comment]
Thanks for the update on this.
I can try to submit a PR.

You want it similar to ruff fix? Meaning a ruff_format: bool setting, if True, run ruff format? Sounds easy enough.

**Comment by provinzkraut** [comment]
> You want it similar to ruff fix? Meaning a ruff_format: bool setting, if True, run ruff format? Sounds easy enough.

Yup, exactly. I was planning to make this a bit more modular, so you could run arbitrary fixes on the code after the fact (e.g. use black or isort instead of ruff), but that doesn't have to be introduced here.
