### ISSUE TITLE
Feature: Add `ruff_format` option

### ISSUE THREAD

**Issue by afuetterer** [provinzkraut/unasyncd#29]
See previous discussion in #27.

**Comment by afuetterer** [comment]
I started to work on this and added additional flags/options "ruff_format" the configuration.

How about the `TreeTransformer`'s `_run_ruff` method? Should there be two or should this one by parametrized to call fix or format? What do you think?

**Comment by provinzkraut** [comment]
> How about the `TreeTransformer`'s `_run_ruff` method? Should there be two or should this one by parametrized to call fix or format? What do you think?

Most of the code can probably be reused so one method that deals with invoking ruff and such and then another method that calls that with `check --fix` and `format` sounds good.
